/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2026-09-20 17:31:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Sign In - PraveenMart</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/theme.css?v=1.1\">\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            min-height: 100vh;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            background-color: var(--color-background);\n");
      out.write("            padding: 2rem 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .auth-wrapper {\n");
      out.write("            width: 100%;\n");
      out.write("            max-width: 440px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .auth-card {\n");
      out.write("            background-color: var(--color-surface-container);\n");
      out.write("            border: 1px solid var(--color-outline-variant);\n");
      out.write("            border-radius: var(--radius-xl);\n");
      out.write("            padding: 2.5rem 2.2rem;\n");
      out.write("            box-shadow: var(--shadow-soft);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .auth-brand {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            gap: 0.5rem;\n");
      out.write("            font-family: var(--font-headline);\n");
      out.write("            font-size: 2rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: var(--color-primary);\n");
      out.write("            margin-bottom: 0.5rem;\n");
      out.write("            text-decoration: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .password-toggle-btn {\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            background: transparent !important;\n");
      out.write("            background-color: transparent !important;\n");
      out.write("            border: none !important;\n");
      out.write("            border-width: 0 !important;\n");
      out.write("            outline: none !important;\n");
      out.write("            box-shadow: none !important;\n");
      out.write("            padding: 0 0.95rem;\n");
      out.write("            color: var(--color-on-surface-variant);\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: color 0.18s ease, transform 0.1s ease;\n");
      out.write("            user-select: none;\n");
      out.write("            flex-shrink: 0;\n");
      out.write("            -webkit-appearance: none !important;\n");
      out.write("            appearance: none !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .password-toggle-btn:hover {\n");
      out.write("            color: var(--color-primary);\n");
      out.write("            background: transparent !important;\n");
      out.write("            border: none !important;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .password-toggle-btn:focus,\n");
      out.write("        .password-toggle-btn:active {\n");
      out.write("            background: transparent !important;\n");
      out.write("            border: none !important;\n");
      out.write("            outline: none !important;\n");
      out.write("            box-shadow: none !important;\n");
      out.write("            transform: scale(0.92);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .password-toggle-btn .material-symbols-outlined {\n");
      out.write("            font-size: 1.28rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .options-row {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            font-size: 0.85rem;\n");
      out.write("            color: var(--color-on-surface-variant);\n");
      out.write("            margin-top: 1rem;\n");
      out.write("            margin-bottom: 1.5rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .remember-me {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.4rem;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .remember-me input {\n");
      out.write("            accent-color: var(--color-primary);\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"auth-wrapper\">\n");
      out.write("    <div class=\"auth-card\">\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/\" class=\"auth-brand\">\n");
      out.write("            <span>PraveenMart</span>\n");
      out.write("        </a>\n");
      out.write("        <p style=\"text-align: center; color: var(--color-on-surface-variant); font-size: 0.92rem; margin-bottom: 2rem;\">\n");
      out.write("            Sign in to access your account & orders\n");
      out.write("        </p>\n");
      out.write("\n");
      out.write("        ");
 if (request.getAttribute("error") != null) { 
      out.write("\n");
      out.write("            <div class=\"alert-box alert-box-error\">\n");
      out.write("                <span class=\"material-symbols-outlined\">warning</span>\n");
      out.write("                <span>");
      out.print( request.getAttribute("error") );
      out.write("</span>\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        ");
 if (request.getAttribute("success") != null) { 
      out.write("\n");
      out.write("            <div class=\"alert-box alert-box-success\">\n");
      out.write("                <span class=\"material-symbols-outlined\">check_circle</span>\n");
      out.write("                <span>");
      out.print( request.getAttribute("success") );
      out.write("</span>\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        <form action=\"login\" method=\"post\">\n");
      out.write("            <label class=\"form-label\" for=\"role\">Select Role</label>\n");
      out.write("            <div class=\"form-input-group\">\n");
      out.write("                <div class=\"form-input-icon\">\n");
      out.write("                    <span class=\"material-symbols-outlined\">badge</span>\n");
      out.write("                </div>\n");
      out.write("                <select class=\"form-select-field\" id=\"role\" name=\"role\" required>\n");
      out.write("                    <option value=\"CUSTOMER\" selected>Customer</option>\n");
      out.write("                    <option value=\"SELLER\">Seller</option>\n");
      out.write("                </select>\n");
      out.write("                <div class=\"form-select-arrow\">\n");
      out.write("                    <span class=\"material-symbols-outlined\">expand_more</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <label class=\"form-label\" for=\"email\">Email Address</label>\n");
      out.write("            <div class=\"form-input-group\">\n");
      out.write("                <div class=\"form-input-icon\">\n");
      out.write("                    <span class=\"material-symbols-outlined\">mail</span>\n");
      out.write("                </div>\n");
      out.write("                <input type=\"email\" class=\"form-input-field\" id=\"email\" name=\"email\" placeholder=\"e.g. user@example.com\" required autocomplete=\"email\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <label class=\"form-label\" for=\"password\">Password</label>\n");
      out.write("            <div class=\"form-input-group\">\n");
      out.write("                <div class=\"form-input-icon\">\n");
      out.write("                    <span class=\"material-symbols-outlined\">lock</span>\n");
      out.write("                </div>\n");
      out.write("                <input type=\"password\" class=\"form-input-field\" id=\"password\" name=\"password\" placeholder=\"Enter your password\" minlength=\"8\" required autocomplete=\"current-password\">\n");
      out.write("                <button type=\"button\" class=\"password-toggle-btn\" id=\"togglePasswordBtn\" title=\"Show password\" aria-label=\"Show password\" tabindex=\"-1\" style=\"background: transparent !important; background-color: transparent !important; border: none !important; border-width: 0 !important; outline: none !important; box-shadow: none !important; padding: 0 0.95rem; cursor: pointer; display: inline-flex; align-items: center; justify-content: center; color: var(--color-on-surface-variant); -webkit-appearance: none !important; appearance: none !important;\">\n");
      out.write("                    <span class=\"material-symbols-outlined\" id=\"togglePasswordIcon\">visibility</span>\n");
      out.write("                </button>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"options-row\">\n");
      out.write("                <label class=\"remember-me\">\n");
      out.write("                    <input type=\"checkbox\" name=\"remember\" checked>\n");
      out.write("                    <span>Remember me</span>\n");
      out.write("                </label>\n");
      out.write("                <label style=\"display: flex; align-items: center; gap: 0.35rem; cursor: pointer; font-size: 0.85rem; color: var(--color-on-surface-variant); user-select: none;\">\n");
      out.write("                    <input type=\"checkbox\" id=\"showPasswordCheckbox\" style=\"accent-color: var(--color-primary); cursor: pointer;\">\n");
      out.write("                    <span>Show password</span>\n");
      out.write("                </label>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <button type=\"submit\" class=\"btn btn-primary btn-pill\" style=\"width: 100%; padding: 0.95rem; font-size: 1rem;\">\n");
      out.write("                <span>Sign In</span>\n");
      out.write("                <span class=\"material-symbols-outlined\">arrow_forward</span>\n");
      out.write("            </button>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <div style=\"margin-top: 2rem; text-align: center; font-size: 0.9rem; color: var(--color-on-surface-variant);\">\n");
      out.write("            Don't have an account?\n");
      out.write("            <a href=\"register.jsp\" style=\"font-weight: 700; text-decoration: underline;\">Create Account</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    (function() {\n");
      out.write("        const pwdInput = document.getElementById('password');\n");
      out.write("        const toggleBtn = document.getElementById('togglePasswordBtn');\n");
      out.write("        const toggleIcon = document.getElementById('togglePasswordIcon');\n");
      out.write("        const showCb = document.getElementById('showPasswordCheckbox');\n");
      out.write("\n");
      out.write("        if (!pwdInput) return;\n");
      out.write("\n");
      out.write("        function setVisibility(show) {\n");
      out.write("            pwdInput.type = show ? 'text' : 'password';\n");
      out.write("            if (toggleIcon) {\n");
      out.write("                toggleIcon.textContent = show ? 'visibility_off' : 'visibility';\n");
      out.write("            }\n");
      out.write("            if (toggleBtn) {\n");
      out.write("                toggleBtn.setAttribute('title', show ? 'Hide password' : 'Show password');\n");
      out.write("                toggleBtn.setAttribute('aria-label', show ? 'Hide password' : 'Show password');\n");
      out.write("            }\n");
      out.write("            if (showCb && showCb.checked !== show) {\n");
      out.write("                showCb.checked = show;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        if (toggleBtn) {\n");
      out.write("            toggleBtn.addEventListener('click', function(e) {\n");
      out.write("                e.preventDefault();\n");
      out.write("                const willShow = pwdInput.type === 'password';\n");
      out.write("                setVisibility(willShow);\n");
      out.write("                pwdInput.focus();\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        if (showCb) {\n");
      out.write("            showCb.addEventListener('change', function() {\n");
      out.write("                setVisibility(showCb.checked);\n");
      out.write("                pwdInput.focus();\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("    })();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
