/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2026-09-20 17:30:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.text.NumberFormat;
import java.util.Locale;
import java.math.BigDecimal;
import com.praveen.praveenmart.model.Product;
import com.praveen.praveenmart.model.User;
import com.praveen.praveenmart.model.User;
import com.praveen.praveenmart.service.CartService;

public final class store_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/footer.jspf", Long.valueOf(1789925011384L));
    _jspx_dependants.put("/includes/header.jspf", Long.valueOf(1789925027992L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.math.BigDecimal");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("com.praveen.praveenmart.model.Product");
    _jspx_imports_classes.add("com.praveen.praveenmart.service.CartService");
    _jspx_imports_classes.add("com.praveen.praveenmart.model.User");
    _jspx_imports_classes.add("java.text.NumberFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    List<Product> products = (List<Product>) request.getAttribute("products");
    String selectedCategory = (String) request.getAttribute("selectedCategory");
    String searchQuery = (String) request.getAttribute("searchQuery");
    if (selectedCategory == null) selectedCategory = "all";
    if (searchQuery == null) searchQuery = "";

    String cartMessage = (String) session.getAttribute("cartMessage");
    String cartError = (String) session.getAttribute("cartError");
    session.removeAttribute("cartMessage");
    session.removeAttribute("cartError");

    NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("en", "IN"));

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>PraveenMart - Organic & Artisan Marketplace</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/theme.css\">\n");
      out.write("    <style>\n");
      out.write("        .hero-banner {\n");
      out.write("            background: linear-gradient(135deg, var(--color-surface-container) 0%, var(--color-surface-container-low) 100%);\n");
      out.write("            border-bottom: 1px solid var(--color-outline-variant);\n");
      out.write("            padding: 2.2rem 0 1.8rem;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero-title {\n");
      out.write("            font-size: 2.8rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: var(--color-on-surface);\n");
      out.write("            margin-bottom: 0.8rem;\n");
      out.write("            letter-spacing: -0.02em;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero-subtitle {\n");
      out.write("            font-size: 1.15rem;\n");
      out.write("            color: var(--color-on-surface-variant);\n");
      out.write("            max-width: 600px;\n");
      out.write("            margin: 0 auto 2rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-bar-wrapper {\n");
      out.write("            max-width: 620px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-form {\n");
      out.write("            display: flex;\n");
      out.write("            background: #FFFFFF;\n");
      out.write("            border: 1px solid var(--color-outline-variant);\n");
      out.write("            border-radius: var(--radius-pill);\n");
      out.write("            padding: 0.35rem 0.5rem 0.35rem 1.4rem;\n");
      out.write("            box-shadow: var(--shadow-md);\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-form:focus-within {\n");
      out.write("            border-color: var(--color-primary);\n");
      out.write("            box-shadow: 0 6px 24px rgba(74, 124, 89, 0.18);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .search-input {\n");
      out.write("            flex: 1;\n");
      out.write("            border: none;\n");
      out.write("            outline: none;\n");
      out.write("            font-size: 1rem;\n");
      out.write("            font-family: var(--font-body);\n");
      out.write("            background: transparent;\n");
      out.write("            color: var(--color-on-surface);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .category-pills {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            gap: 0.6rem;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("            margin: 2.5rem 0 1rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .category-pill {\n");
      out.write("            padding: 0.5rem 1.25rem;\n");
      out.write("            border-radius: var(--radius-pill);\n");
      out.write("            font-size: 0.9rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            background-color: var(--color-surface-container);\n");
      out.write("            color: var(--color-on-surface-variant);\n");
      out.write("            border: 1px solid var(--color-outline-variant);\n");
      out.write("            text-decoration: none;\n");
      out.write("            transition: all 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .category-pill:hover, .category-pill.active {\n");
      out.write("            background-color: var(--color-primary);\n");
      out.write("            color: #FFFFFF;\n");
      out.write("            border-color: var(--color-primary);\n");
      out.write("            box-shadow: var(--shadow-soft);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .products-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(270px, 1fr));\n");
      out.write("            gap: 2rem;\n");
      out.write("            padding: 2.5rem 0 4rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-card {\n");
      out.write("            background-color: var(--color-surface-card);\n");
      out.write("            border: 1px solid var(--color-outline-variant);\n");
      out.write("            border-radius: var(--radius-lg);\n");
      out.write("            overflow: hidden;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            transition: transform 0.2s ease, box-shadow 0.2s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-card:hover {\n");
      out.write("            transform: translateY(-4px);\n");
      out.write("            box-shadow: var(--shadow-hover);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-image-box {\n");
      out.write("            height: 220px;\n");
      out.write("            width: 100%;\n");
      out.write("            background-color: var(--color-surface-container);\n");
      out.write("            position: relative;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-image-box img {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 100%;\n");
      out.write("            object-fit: cover;\n");
      out.write("            transition: transform 0.3s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-card:hover .product-image-box img {\n");
      out.write("            transform: scale(1.05);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-content {\n");
      out.write("            padding: 1.25rem;\n");
      out.write("            display: flex;\n");
      out.write("            flex-direction: column;\n");
      out.write("            flex: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-category-tag {\n");
      out.write("            font-size: 0.75rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            text-transform: uppercase;\n");
      out.write("            letter-spacing: 0.05em;\n");
      out.write("            color: var(--color-primary);\n");
      out.write("            margin-bottom: 0.3rem;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-title {\n");
      out.write("            font-family: var(--font-headline);\n");
      out.write("            font-size: 1.15rem;\n");
      out.write("            font-weight: 600;\n");
      out.write("            color: var(--color-on-surface);\n");
      out.write("            margin-bottom: 0.4rem;\n");
      out.write("            text-decoration: none;\n");
      out.write("            display: -webkit-box;\n");
      out.write("            -webkit-line-clamp: 1;\n");
      out.write("            -webkit-box-orient: vertical;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-title:hover {\n");
      out.write("            color: var(--color-primary);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-desc {\n");
      out.write("            font-size: 0.85rem;\n");
      out.write("            color: var(--color-on-surface-variant);\n");
      out.write("            margin-bottom: 1rem;\n");
      out.write("            display: -webkit-box;\n");
      out.write("            -webkit-line-clamp: 2;\n");
      out.write("            -webkit-box-orient: vertical;\n");
      out.write("            overflow: hidden;\n");
      out.write("            flex: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-footer {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            margin-top: auto;\n");
      out.write("            padding-top: 0.75rem;\n");
      out.write("            border-top: 1px solid var(--color-surface-container);\n");
      out.write("            gap: 0.5rem;\n");
      out.write("            flex-wrap: wrap;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .product-price {\n");
      out.write("            font-size: 1.2rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: var(--color-neutral-dark);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-qty-stepper {\n");
      out.write("            display: inline-flex;\n");
      out.write("            align-items: center;\n");
      out.write("            border: 1px solid var(--color-outline-variant);\n");
      out.write("            border-radius: var(--radius-pill);\n");
      out.write("            background: var(--color-surface-container);\n");
      out.write("            overflow: hidden;\n");
      out.write("            height: 32px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-qty-stepper .qty-btn {\n");
      out.write("            background: transparent;\n");
      out.write("            border: none;\n");
      out.write("            width: 26px;\n");
      out.write("            height: 100%;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            font-size: 1rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: var(--color-on-surface);\n");
      out.write("            cursor: pointer;\n");
      out.write("            transition: background-color 0.15s ease, color 0.15s ease;\n");
      out.write("            user-select: none;\n");
      out.write("            padding: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-qty-stepper .qty-btn:hover {\n");
      out.write("            background: rgba(13, 71, 34, 0.12);\n");
      out.write("            color: var(--color-primary);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-qty-stepper .qty-btn:active {\n");
      out.write("            transform: scale(0.92);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-qty-stepper .qty-input-field {\n");
      out.write("            width: 26px;\n");
      out.write("            border: none;\n");
      out.write("            background: transparent;\n");
      out.write("            text-align: center;\n");
      out.write("            font-size: 0.85rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: var(--color-on-surface);\n");
      out.write("            -moz-appearance: textfield;\n");
      out.write("            padding: 0;\n");
      out.write("            pointer-events: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .card-qty-stepper .qty-input-field::-webkit-outer-spin-button,\n");
      out.write("        .card-qty-stepper .qty-input-field::-webkit-inner-spin-button {\n");
      out.write("            -webkit-appearance: none;\n");
      out.write("            margin: 0;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write('\n');
      out.write('\n');
      out.write('\n');

    User sessionUser = (User) session.getAttribute("user");
    int cartCount = 0;
    if (sessionUser != null) {
        try {
            CartService headerCartService = new CartService();
            cartCount = headerCartService.getCartItemCount(sessionUser.getId());
        } catch (Exception ignored) {}
    }

      out.write("\n");
      out.write("<style>\n");
      out.write("    .site-header .container {\n");
      out.write("        max-width: 100% !important;\n");
      out.write("        width: 100% !important;\n");
      out.write("        padding-left: 1rem !important;\n");
      out.write("        padding-right: 1.5rem !important;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .nav-left {\n");
      out.write("        display: flex;\n");
      out.write("        align-items: center;\n");
      out.write("        gap: 0.85rem;\n");
      out.write("        margin-left: 0;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .menu-dropdown-wrapper {\n");
      out.write("        position: relative;\n");
      out.write("        display: inline-flex;\n");
      out.write("        align-items: center;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .menu-toggle-btn {\n");
      out.write("        cursor: pointer;\n");
      out.write("        background-color: var(--color-surface-container);\n");
      out.write("        border: 1px solid var(--color-outline-variant);\n");
      out.write("        color: var(--color-on-surface);\n");
      out.write("        transition: all 0.2s cubic-bezier(0.16, 1, 0.3, 1);\n");
      out.write("        user-select: none;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .menu-toggle-btn:hover,\n");
      out.write("    .menu-toggle-btn.active {\n");
      out.write("        background-color: var(--color-primary);\n");
      out.write("        border-color: var(--color-primary);\n");
      out.write("        color: #ffffff;\n");
      out.write("        box-shadow: 0 4px 12px rgba(176, 96, 0, 0.25);\n");
      out.write("        transform: translateY(-1px);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .menu-dropdown-card {\n");
      out.write("        position: absolute;\n");
      out.write("        top: calc(100% + 0.65rem);\n");
      out.write("        left: 0;\n");
      out.write("        min-width: 200px;\n");
      out.write("        background-color: var(--color-surface-container-high, #ffffff);\n");
      out.write("        border: 1px solid var(--color-outline-variant);\n");
      out.write("        border-radius: var(--radius-lg);\n");
      out.write("        box-shadow: 0 14px 34px rgba(44, 30, 16, 0.14), 0 2px 8px rgba(44, 30, 16, 0.06);\n");
      out.write("        padding: 0.4rem;\n");
      out.write("        z-index: 1000;\n");
      out.write("        display: none;\n");
      out.write("        flex-direction: column;\n");
      out.write("        gap: 0.25rem;\n");
      out.write("        animation: menuDropdownFade 0.2s cubic-bezier(0.16, 1, 0.3, 1) forwards;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    @keyframes menuDropdownFade {\n");
      out.write("        from {\n");
      out.write("            opacity: 0;\n");
      out.write("            transform: translateY(-8px) scale(0.97);\n");
      out.write("        }\n");
      out.write("        to {\n");
      out.write("            opacity: 1;\n");
      out.write("            transform: translateY(0) scale(1);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .menu-dropdown-card.show {\n");
      out.write("        display: flex;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .menu-dropdown-item {\n");
      out.write("        display: flex;\n");
      out.write("        align-items: center;\n");
      out.write("        gap: 0.75rem;\n");
      out.write("        padding: 0.65rem 0.85rem;\n");
      out.write("        color: var(--color-on-surface);\n");
      out.write("        text-decoration: none;\n");
      out.write("        font-size: 0.95rem;\n");
      out.write("        font-weight: 600;\n");
      out.write("        border-radius: var(--radius-md);\n");
      out.write("        transition: all 0.18s ease;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .menu-dropdown-item .material-symbols-outlined {\n");
      out.write("        font-size: 1.28rem;\n");
      out.write("        color: var(--color-primary);\n");
      out.write("        transition: transform 0.18s ease;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .menu-dropdown-item:hover {\n");
      out.write("        background-color: var(--color-surface-container);\n");
      out.write("        color: var(--color-primary);\n");
      out.write("        transform: translateX(4px);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .menu-dropdown-item:hover .material-symbols-outlined {\n");
      out.write("        transform: scale(1.12);\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("<header class=\"site-header\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"nav-bar\">\n");
      out.write("            <!-- Left Group: Three-line Menu + Brand Logo -->\n");
      out.write("            <div class=\"nav-left\">\n");
      out.write("                <!-- Three-Line Menu Bar (Top Left) -->\n");
      out.write("                <div class=\"menu-dropdown-wrapper\" id=\"menuDropdownWrapper\">\n");
      out.write("                    <button type=\"button\" class=\"nav-icon-btn menu-toggle-btn\" id=\"menuToggleBtn\" aria-label=\"Toggle navigation menu\" aria-expanded=\"false\" title=\"Menu\">\n");
      out.write("                        <span class=\"material-symbols-outlined\" id=\"menuToggleIcon\" style=\"font-size: 1.4rem;\">menu</span>\n");
      out.write("                    </button>\n");
      out.write("                    <div class=\"menu-dropdown-card\" id=\"menuDropdownCard\" role=\"menu\">\n");
      out.write("                        ");
 if (sessionUser == null || !"ADMIN".equalsIgnoreCase(sessionUser.getRole())) { 
      out.write("\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/products\" class=\"menu-dropdown-item\" role=\"menuitem\">\n");
      out.write("                                <span class=\"material-symbols-outlined\">storefront</span>\n");
      out.write("                                <span>Shop</span>\n");
      out.write("                            </a>\n");
      out.write("                            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/orders\" class=\"menu-dropdown-item\" role=\"menuitem\">\n");
      out.write("                                <span class=\"material-symbols-outlined\">receipt_long</span>\n");
      out.write("                                <span>My Orders</span>\n");
      out.write("                            </a>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                        ");
 if (sessionUser != null) { 
      out.write("\n");
      out.write("                            ");
 if ("SELLER".equalsIgnoreCase(sessionUser.getRole())) { 
      out.write("\n");
      out.write("                                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/seller/dashboard\" class=\"menu-dropdown-item\" role=\"menuitem\">\n");
      out.write("                                    <span class=\"material-symbols-outlined\">store</span>\n");
      out.write("                                    <span>Seller Hub</span>\n");
      out.write("                                </a>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                            ");
 if ("ADMIN".equalsIgnoreCase(sessionUser.getRole()) && "admin@praveenmart.com".equalsIgnoreCase(sessionUser.getEmail())) { 
      out.write("\n");
      out.write("                                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/admin/dashboard\" class=\"menu-dropdown-item\" role=\"menuitem\" style=\"color: #b06000;\">\n");
      out.write("                                    <span class=\"material-symbols-outlined\">admin_panel_settings</span>\n");
      out.write("                                    <span>Admin Panel</span>\n");
      out.write("                                </a>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Brand Logo -->\n");
      out.write("                <a href=\"");
      out.print( (sessionUser != null && "ADMIN".equalsIgnoreCase(sessionUser.getRole())) ? request.getContextPath() + "/admin/dashboard" : request.getContextPath() + "/products" );
      out.write("\" class=\"brand-logo\">\n");
      out.write("                    <span>PraveenMart</span>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- User Authentication & Cart Actions -->\n");
      out.write("            <div class=\"nav-actions\">\n");
      out.write("                ");
 if (sessionUser != null) { 
      out.write("\n");
      out.write("                    ");
 if (!"ADMIN".equalsIgnoreCase(sessionUser.getRole())) { 
      out.write("\n");
      out.write("                        <!-- Cart Button with Count Badge -->\n");
      out.write("                        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/cart\" class=\"nav-icon-btn\" id=\"navCartBtn\" title=\"View Cart\">\n");
      out.write("                            <span class=\"material-symbols-outlined\" style=\"font-size: 1.3rem;\">shopping_bag</span>\n");
      out.write("                            <span class=\"nav-badge-count\" id=\"navCartBadge\" ");
      out.print( cartCount > 0 ? "" : "style=\"display: none;\"" );
      out.write('>');
      out.print( cartCount );
      out.write("</span>\n");
      out.write("                        </a>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                    <!-- User Account / Profile -->\n");
      out.write("                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/dashboard.jsp\" class=\"btn btn-secondary btn-pill\" style=\"padding: 0.45rem 1.1rem; font-size: 0.88rem;\" title=\"");
      out.print( sessionUser.getEmail() );
      out.write("\">\n");
      out.write("                        <span class=\"material-symbols-outlined\" style=\"font-size: 1.15rem; color: var(--color-primary);\">account_circle</span>\n");
      out.write("                        <span>");
      out.print( sessionUser.getName() );
      out.write("</span>\n");
      out.write("                    </a>\n");
      out.write("\n");
      out.write("                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/logout\" class=\"btn btn-outlined btn-pill\" style=\"padding: 0.45rem 0.9rem; font-size: 0.85rem;\">\n");
      out.write("                        <span>Sign Out</span>\n");
      out.write("                    </a>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                    <!-- Cart Button for visitors -->\n");
      out.write("                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/cart\" class=\"nav-icon-btn\" id=\"navCartBtn\" title=\"View Cart\">\n");
      out.write("                        <span class=\"material-symbols-outlined\" style=\"font-size: 1.3rem;\">shopping_bag</span>\n");
      out.write("                        <span class=\"nav-badge-count\" id=\"navCartBadge\" style=\"display: none;\">0</span>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/login.jsp\" class=\"btn btn-primary btn-pill\" style=\"padding: 0.45rem 1.2rem; font-size: 0.88rem;\">\n");
      out.write("                        <span class=\"material-symbols-outlined\" style=\"font-size: 1.15rem;\">login</span>\n");
      out.write("                        <span>Sign In</span>\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/register.jsp\" class=\"btn btn-secondary btn-pill\" style=\"padding: 0.45rem 1.1rem; font-size: 0.88rem;\">\n");
      out.write("                        <span>Register</span>\n");
      out.write("                    </a>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    (function() {\n");
      out.write("        const toggleBtn = document.getElementById('menuToggleBtn');\n");
      out.write("        const dropdownCard = document.getElementById('menuDropdownCard');\n");
      out.write("        const wrapper = document.getElementById('menuDropdownWrapper');\n");
      out.write("\n");
      out.write("        if (!toggleBtn || !dropdownCard) return;\n");
      out.write("\n");
      out.write("        function toggleMenu(e) {\n");
      out.write("            e.stopPropagation();\n");
      out.write("            const isOpen = dropdownCard.classList.contains('show');\n");
      out.write("            if (isOpen) {\n");
      out.write("                closeMenu();\n");
      out.write("            } else {\n");
      out.write("                openMenu();\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function openMenu() {\n");
      out.write("            dropdownCard.classList.add('show');\n");
      out.write("            toggleBtn.classList.add('active');\n");
      out.write("            toggleBtn.setAttribute('aria-expanded', 'true');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function closeMenu() {\n");
      out.write("            dropdownCard.classList.remove('show');\n");
      out.write("            toggleBtn.classList.remove('active');\n");
      out.write("            toggleBtn.setAttribute('aria-expanded', 'false');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        toggleBtn.addEventListener('click', toggleMenu);\n");
      out.write("\n");
      out.write("        document.addEventListener('click', function(e) {\n");
      out.write("            if (wrapper && !wrapper.contains(e.target)) {\n");
      out.write("                closeMenu();\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        document.addEventListener('keydown', function(e) {\n");
      out.write("            if (e.key === 'Escape') {\n");
      out.write("                closeMenu();\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    })();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<section class=\"hero-banner\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("\n");
      out.write("        <div class=\"search-bar-wrapper\">\n");
      out.write("            <form action=\"");
      out.print( request.getContextPath() );
      out.write("/products\" method=\"get\" class=\"search-form\">\n");
      out.write("                <input type=\"text\" name=\"q\" class=\"search-input\" placeholder=\"Search products, descriptions, keywords...\" value=\"");
      out.print( searchQuery );
      out.write("\">\n");
      out.write("                ");
 if (!"all".equalsIgnoreCase(selectedCategory)) { 
      out.write("\n");
      out.write("                    <input type=\"hidden\" name=\"category\" value=\"");
      out.print( selectedCategory );
      out.write("\">\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary btn-pill\" style=\"padding: 0.6rem 1.4rem;\">\n");
      out.write("                    <span class=\"material-symbols-outlined\">search</span>\n");
      out.write("                    <span>Search</span>\n");
      out.write("                </button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"category-pills\">\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/products\" class=\"category-pill ");
      out.print( "all".equalsIgnoreCase(selectedCategory) ? "active" : "" );
      out.write("\">All Products</a>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/products?category=Fashion%20%26%20Style");
      out.print( !searchQuery.isEmpty() ? "&q=" + searchQuery : "" );
      out.write("\" class=\"category-pill ");
      out.print( selectedCategory != null && (selectedCategory.toLowerCase().contains("fashion") || selectedCategory.toLowerCase().contains("apparel") || selectedCategory.toLowerCase().contains("style")) ? "active" : "" );
      out.write("\">Fashion & Style</a>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/products?category=Home%20%26%20Kitchen");
      out.print( !searchQuery.isEmpty() ? "&q=" + searchQuery : "" );
      out.write("\" class=\"category-pill ");
      out.print( selectedCategory != null && (selectedCategory.toLowerCase().contains("home") || selectedCategory.toLowerCase().contains("kitchen")) ? "active" : "" );
      out.write("\">Home & Kitchen</a>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/products?category=Electronics");
      out.print( !searchQuery.isEmpty() ? "&q=" + searchQuery : "" );
      out.write("\" class=\"category-pill ");
      out.print( "Electronics".equalsIgnoreCase(selectedCategory) ? "active" : "" );
      out.write("\">Electronics</a>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/products?category=Accessories");
      out.print( !searchQuery.isEmpty() ? "&q=" + searchQuery : "" );
      out.write("\" class=\"category-pill ");
      out.print( "Accessories".equalsIgnoreCase(selectedCategory) ? "active" : "" );
      out.write("\">Accessories</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<main class=\"container\">\n");
      out.write("    ");
 if (cartMessage != null) { 
      out.write("\n");
      out.write("        <div class=\"alert-box alert-box-success\" style=\"margin-top: 1.5rem;\">\n");
      out.write("            <span class=\"material-symbols-outlined\">check_circle</span>\n");
      out.write("            <span>");
      out.print( cartMessage );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    ");
 if (cartError != null) { 
      out.write("\n");
      out.write("        <div class=\"alert-box alert-box-error\" style=\"margin-top: 1.5rem;\">\n");
      out.write("            <span class=\"material-symbols-outlined\">warning</span>\n");
      out.write("            <span>");
      out.print( cartError );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"products-grid\">\n");
      out.write("        ");
 if (products != null && !products.isEmpty()) { 
      out.write("\n");
      out.write("            ");
 for (Product p : products) { 
      out.write("\n");
      out.write("                <div class=\"product-card\">\n");
      out.write("                    <div class=\"product-image-box\">\n");
      out.write("                        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/product-details?id=");
      out.print( p.getId() );
      out.write("\">\n");
      out.write("                            ");
 if (p.getImageUrl() != null && !p.getImageUrl().isBlank()) { 
      out.write("\n");
      out.write("                                <img src=\"");
      out.print( p.getImageUrl() );
      out.write("\" alt=\"");
      out.print( p.getName() );
      out.write("\" onerror=\"this.src='https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80'\">\n");
      out.write("                            ");
 } else { 
      out.write("\n");
      out.write("                                <img src=\"https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80\" alt=\"Product Placeholder\">\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </a>\n");
      out.write("                        <div style=\"position: absolute; top: 12px; right: 12px;\">\n");
      out.write("                            ");
 if (p.getStockQty() > 10) { 
      out.write("\n");
      out.write("                                <span class=\"badge-tag badge-in-stock\">In Stock</span>\n");
      out.write("                            ");
 } else if (p.getStockQty() > 0) { 
      out.write("\n");
      out.write("                                <span class=\"badge-tag badge-low-stock\">Only ");
      out.print( p.getStockQty() );
      out.write(" Left</span>\n");
      out.write("                            ");
 } else { 
      out.write("\n");
      out.write("                                <span class=\"badge-tag badge-out-stock\">Sold Out</span>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"product-content\">\n");
      out.write("                        <div style=\"display: flex; align-items: center; justify-content: space-between; margin-bottom: 0.4rem;\">\n");
      out.write("                            <div class=\"product-category-tag\">");
      out.print( p.getCategory() );
      out.write("</div>\n");
      out.write("                            ");
 
                                double ratingVal = 4.3 + ((p.getId() != null ? p.getId() : 1) % 7) * 0.1;
                                if (ratingVal > 4.9) ratingVal = 4.9;
                                int reviewCount = 85 + (int)((p.getId() != null ? p.getId() : 1) * 43) % 450;
                            
      out.write("\n");
      out.write("                            <div style=\"display: flex; align-items: center; gap: 0.3rem;\">\n");
      out.write("                                <span style=\"background-color: #388e3c; color: #FFFFFF; font-size: 0.75rem; font-weight: 700; padding: 0.15rem 0.45rem; border-radius: 4px; display: inline-flex; align-items: center; gap: 0.15rem;\">\n");
      out.write("                                    ");
      out.print( String.format(Locale.US, "%.1f", ratingVal) );
      out.write(" ★\n");
      out.write("                                </span>\n");
      out.write("                                <span style=\"font-size: 0.78rem; color: var(--color-on-surface-variant); font-weight: 600;\">(");
      out.print( reviewCount );
      out.write(")</span>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/product-details?id=");
      out.print( p.getId() );
      out.write("\" class=\"product-title\">\n");
      out.write("                            ");
      out.print( p.getName() );
      out.write("\n");
      out.write("                        </a>\n");
      out.write("                        <p class=\"product-desc\">");
      out.print( p.getDescription() != null ? p.getDescription() : "Authentic craft item." );
      out.write("</p>\n");
      out.write("\n");
      out.write("                        <div style=\"margin-top: 0.4rem; font-size: 0.78rem; color: #1e7e34; font-weight: 700; display: flex; align-items: center; gap: 0.25rem;\">\n");
      out.write("                            <span class=\"material-symbols-outlined\" style=\"font-size: 0.95rem;\">local_shipping</span>\n");
      out.write("                            <span>Free Express Delivery</span>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"product-footer\" style=\"margin-top: 0.8rem;\">\n");
      out.write("                            <div>\n");
      out.write("                                <div class=\"product-price\">\n");
      out.write("                                    ");
      out.print( currencyFormat.format(p.getPrice() != null ? p.getPrice() : BigDecimal.ZERO) );
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                                <div style=\"font-size: 0.78rem; color: var(--color-on-surface-variant);\">\n");
      out.write("                                    M.R.P.: <span style=\"text-decoration: line-through;\">");
      out.print( currencyFormat.format((p.getPrice() != null ? p.getPrice() : BigDecimal.ZERO).multiply(new BigDecimal("1.4"))) );
      out.write("</span>\n");
      out.write("                                    <span style=\"color: #388e3c; font-weight: 700; margin-left: 0.2rem;\">40% OFF</span>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            ");
 if (p.getStockQty() > 0) { 
      out.write("\n");
      out.write("                                <form action=\"");
      out.print( request.getContextPath() );
      out.write("/cart/add\" method=\"post\" class=\"add-to-cart-form\"\n");
      out.write("                                      data-product-id=\"");
      out.print( p.getId() );
      out.write("\"\n");
      out.write("                                      data-product-name=\"");
      out.print( p.getName().replace("\"", "&quot;") );
      out.write("\"\n");
      out.write("                                      data-product-price=\"");
      out.print( currencyFormat.format(p.getPrice() != null ? p.getPrice() : BigDecimal.ZERO) );
      out.write("\"\n");
      out.write("                                      data-product-category=\"");
      out.print( p.getCategory() != null ? p.getCategory().replace("\"", "&quot;") : "" );
      out.write("\"\n");
      out.write("                                      data-product-image=\"");
      out.print( p.getImageUrl() != null ? p.getImageUrl() : "" );
      out.write("\"\n");
      out.write("                                      style=\"display: flex; align-items: center; gap: 0.4rem;\">\n");
      out.write("                                    <input type=\"hidden\" name=\"productId\" value=\"");
      out.print( p.getId() );
      out.write("\">\n");
      out.write("                                    <div class=\"card-qty-stepper\">\n");
      out.write("                                        <button type=\"button\" class=\"qty-btn qty-btn-minus\" aria-label=\"Decrease quantity\">−</button>\n");
      out.write("                                        <input type=\"number\" name=\"quantity\" class=\"qty-input-field\" value=\"1\" min=\"1\" max=\"");
      out.print( p.getStockQty() );
      out.write("\" readonly>\n");
      out.write("                                        <button type=\"button\" class=\"qty-btn qty-btn-plus\" aria-label=\"Increase quantity\">+</button>\n");
      out.write("                                    </div>\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-primary btn-pill btn-add-cart\" style=\"padding: 0.45rem 0.85rem; font-size: 0.85rem; display: inline-flex; align-items: center; gap: 0.25rem;\">\n");
      out.write("                                        <span class=\"material-symbols-outlined\" style=\"font-size: 1rem;\">add_shopping_cart</span>\n");
      out.write("                                        <span>Add</span>\n");
      out.write("                                    </button>\n");
      out.write("                                </form>\n");
      out.write("                            ");
 } else { 
      out.write("\n");
      out.write("                                <button class=\"btn btn-secondary btn-pill\" disabled style=\"padding: 0.45rem 1rem; font-size: 0.85rem; opacity: 0.6; cursor: not-allowed;\">\n");
      out.write("                                    <span>Unavailable</span>\n");
      out.write("                                </button>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("            <div style=\"grid-column: 1 / -1; text-align: center; padding: 4rem 1rem;\">\n");
      out.write("                <span class=\"material-symbols-outlined\" style=\"font-size: 4rem; color: var(--color-outline); margin-bottom: 1rem;\">search_off</span>\n");
      out.write("                <h3 style=\"margin-bottom: 0.5rem;\">No products found</h3>\n");
      out.write("                <p style=\"color: var(--color-on-surface-variant); margin-bottom: 1.5rem;\">Try adjusting your search query or selecting a different category.</p>\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/products\" class=\"btn btn-primary btn-pill\">Clear All Filters</a>\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"site-footer\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"footer-content\">\n");
      out.write("            <div style=\"display: flex; align-items: center; gap: 1.5rem;\">\n");
      out.write("                <div class=\"font-headline\" style=\"font-size: 2.1rem; font-weight: 800; color: #0d4722;\">PraveenMart</div>\n");
      out.write("                <div style=\"font-size: 0.88rem; color: var(--color-on-surface-variant);\">\n");
      out.write("                    &copy; ");
      out.print( java.time.Year.now().getValue() );
      out.write(" PraveenMart.\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"footer-links\">\n");
      out.write("                <a href=\"#\">Privacy Policy</a>\n");
      out.write("                <a href=\"#\">Terms of Service</a>\n");
      out.write("                <a href=\"#\">Shipping & Returns</a>\n");
      out.write("                <a href=\"#\">Contact Us</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
